version: 0.2

phases:
  install:
    commands:
      - echo Installing global packages...
      - npm install -g serverless dotenv-cli
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - dotenv -c $STAGE sls deploy -s $STAGE --verbose
  post_build:
    commands:
      - echo Deployment completed on `date`
