version: 0.2

phases:
  install:
    commands:
      - echo Installing global packages...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - npx getdotenv -e $ENV -- sls deploy --verbose
  post_build:
    commands:
      - echo Deployment completed on `date`
